sudo: required
language: java
jdk:
- oraclejdk8
before_cache:
- rm -fr $HOME/.gradle/caches/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
- sudo apt-get install jq
- wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest
  | jq -r .assets[0].browser_download_url)
script:
- "./gradlew build"
- "./gradlew codeCoverageReport"
after_success:
- java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter
  -l Java -r build/reports/jacoco/jacocoTestReport.xml
