language: java
jdk:
  - openjdk17

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - "./gradlew build --info"
  - "./gradlew dependencyCheckAnalyze || echo 'dependencyCheckAnalyze failed'"

env:
  global
    - MAX_NUM_PARALLEL_THREADS=2

before_install:
  - curl https://raw.githubusercontent.com/hmcts/cnp-api-docs/master/bin/publish-swagger-group-docs.sh > publish-swagger-group-docs.sh

after_success:
  - 'bash <(curl -s https://codecov.io/bash) || echo "Codecov failed to upload"'
  - '[ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ] && sh ./publish-swagger-group-docs.sh v1_internal v1_external v2_internal v2_external'
