language: java
jdk:
  - oraclejdk8

before_cache:
- rm -fr $HOME/.gradle/caches/

cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"

script:
  - "./gradlew build"
  - "./gradlew dependencyCheckAnalyze || echo 'dependencyCheckAnalyze failed'"
  - "./gradlew sendCoverageToCodacy || echo sendCoverageToCodacy failed"

env:
  global:
    - CODACY_PROJECT_TOKEN=24f7bf62b3fa4328aa3b9bf32c07b0d9

after_success:
  - "bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'"
